[package]
name = "igris"
version = "0.2.0"
authors = ["Keyvan Kambakhsh <keyvankambakhsh@gmail.com>"]
edition = "2021"
description = "Minimal Rust library for training GPT language-models - Igris"
repository = "https://github.com/keyvank/Igris"
homepage = "https://github.com/keyvank/Igris"
license = "MIT"


[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3.3"
rayon = "1.7.0"
thiserror = "1.0"
ocl = { version = "0.19", optional = true }
structopt = { version = "0.3", default-features = false }

[features]
gpu = ["ocl"]
